version: '3.8'
services:
  nginx:
    container_name: diary-nginx
    image: nginx
    restart: always
    networks:
      - diary
    ports:
      - "80:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d/
      - ./logs/nginx/:/var/log/nginx/
    depends_on:
      - mysql
      - server
      - redis       
  server:
    container_name: diary-server
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - diary  
    depends_on:
      - mysql
    volumes:
      - .:/app   
    restart: always  
  mysql:
    container_name: diary-mysql-db
    # mac m1칩
    platform: linux/x86_64
    image: mysql
    env_file: 
      - .local.env
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD= ${DB_PASSWORD}
      - MYSQL_DATABASE= ${DB_DATABASE}
    networks:
      - diary  
    volumes:
      - mysql:/var/lib/mysql
    restart: always  
  redis:
    container_name: diary-redis
    image: redis:latest
    restart: always
    ports:
      - "6379:6397"
    volumes:
      - redis:/var/lib/redis       

#/var/lib/docker/volumes/mysql에 저장
volumes:
  mysql:
  redis:

networks:
  diary:    
              